[package]
name = "gephgui-wry"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
smolscale = "0.3.16"
anyhow = "1.0.44"
mime-sniffer = "0.1.2"
tap = "1.0.1"
mime_guess = "2.0.3"
wry = "0.12.2"
serde_json = "1.0.68"
serde = "1.0.130"
once_cell = "1.8.0"
parking_lot = "0.11.2"
slab = "0.4.4"

[dependencies.rust-embed]
version="6.2"
features=["debug-embed"]

[dependencies.tide]
version="0.16"
default-features=false
features=["h1-server"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
